# SConscript for superstl subdirectory                                                                                                                                                                                                      

# Import envrionment
Import('env')

# Now get list of .cpp files
src_files = Glob('*.cpp')

objs = env.Object(src_files)

Return('objs')

